name: build_wheels
run-name: ${{ github.actor }} is building wheels
on: [workflow_dispatch]
jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
  
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Setup pip
        run: |
           python -m pip install --upgrade pip
           python -m pip install cibuildwheel==1.6.4
         
      - name:  Install
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get update
                    sudo apt-get install gcc g++
               fi
        shell: bash

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*

      - uses: actions/upload-artifact@v6
        with:
          path: ./dist/*.whl
